import './globals.css'
import { Roboto } from 'next/font/google'
import Header from '@/components/core/Header'
import Footer from '@/components/core/Footer'
import '@fortawesome/fontawesome-svg-core/styles.css';

const roboto = Roboto({subsets:['latin'], weight: ['400']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`p-2 m-0 md:m-6 lg:m-8 ${roboto.className} min-h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
